#!/usr/bin/python3
from gpiozero import Button,LED
from signal import pause
from time import sleep
from subprocess import check_call

# 2019-01-01
#pulled from TLF

LEDblue1 = LED(4)
LEDblue2 = LED(17)
LEDyellow = LED(22)
LEDfrontandback = LED(27)
StatusLED = LED(2)

def def_shutdown():
    StatusLED.off()
    check_call("./scripts/playout_controls.sh -c=shutdown", shell=True)

#def def_volU():
 #   check_call("./scripts/playout_controls.sh -c=volumeup", shell=True)

#def def_volD():
#    check_call("./scripts/playout_controls.sh -c=volumedown", shell=True)

#def def_vol0():
#    check_call("./scripts/playout_controls.sh -c=mute", shell=True)

def def_next():
    check_call("./scripts/playout_controls.sh -c=playernext", shell=True)

def def_prev():
    check_call("./scripts/playout_controls.sh -c=playerprev", shell=True)

def def_pause():
    check_call("./scripts/playout_controls.sh -c=playerpause", shell=True)
#funktionierendes LED Script eingefuegt
def def_LED():
	LEDfrontandback.on()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	sleep(0.1)
	LEDblue1.on()
	sleep(0.1)
	LEDblue1.off()
	LEDyellow.on()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	sleep(0.1)
	LEDblue2.on()
	sleep(0.1)
	LEDblue2.off()
	LEDyellow.off()
	sleep(1)
	LEDfrontandback.off()

shut = Button(3)
#vol0 = Button(13)
#volU = Button(16,pull_up=True)
#volD = Button(19,pull_up=True)
next = Button(11) #bei TLF anders als bei RTW 10 vs 11
prev = Button(10) #bei TLF anders als bei RTW 10 vs 11
LED = Button(9)

StatusLED.on()
shut.when_pressed = def_shutdown
#vol0.when_pressed = def_vol0
#volU.when_pressed = def_volU
#volD.when_pressed = def_volD
next.when_pressed = def_next
prev.when_pressed = def_prev
#halt.when_pressed = def_halt
LED.when_pressed = def_LED

pause()

